sonar.projectKey=RaiAkarsh_SpendSmart-Frontend
sonar.organization=raiakarsh
sonar.projectName=Spendsmart Frontend
sonar.projectVersion=1.0

sonar.sourceEncoding=UTF-8
sonar.scm.disabled=true

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/.angular/**,**/*.config.js,**/setup-jest.ts

sonar.typescript.tsconfigPath=tsconfig.sonar.json
sonar.javascript.lcov.reportPaths=coverage/lcov.info
